# Generated by Django 5.0.6 on 2024-06-16 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airbnb', '0002_alter_flat_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='flats/'),
        ),
    ]
