# Generated by Django 5.0.6 on 2024-06-17 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airbnb', '0003_flat_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='price',
            field=models.FloatField(default=100, max_length=6),
            preserve_default=False,
        ),
    ]
