# Generated by Django 5.0.6 on 2024-06-19 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airbnb', '0003_flat_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='price',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
            preserve_default=False,
        ),
    ]
