# Generated by Django 5.0.6 on 2024-06-19 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airbnb', '0004_flat_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flat',
            name='price',
        ),
    ]
